## Data Preparation

Missing Values Repair

In [2]:
import pandas as pd

original_data = pd.read_csv('../data/titanic.csv')

copy_data = original_data.copy()

copy_data.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [12]:
missing_value_columns = ['Age', 'Cabin', 'Embarked']

for col in missing_value_columns:
    print(copy_data[col].isna().value_counts())

Age
False    714
True     177
Name: count, dtype: int64
Cabin
True     687
False    204
Name: count, dtype: int64
Embarked
False    889
True       2
Name: count, dtype: int64

In [13]:
# Removing Cabin Column from the dataset as it has too many missing values

copy_data.drop('Cabin', axis=1, inplace=True)

In [14]:
copy_data.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [54]:
# Assigning the mean value of all the ages for the missing age values

not_missing_values = copy_data[copy_data['Age'].isna() == False]
Average_age = int(not_missing_values['Age'].astype('int').mean())

copy_data['Age'] = copy_data['Age'].fillna(Average_age)

In [55]:
copy_data.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,No_of_Siblings_and_Spouses_Aboard,No_of_Parents_and_Children_Aboard,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [56]:
# Dropping remaining missing values rows

copy_data.dropna(inplace=True)

Renaming the columns

In [57]:
# Renaming the 'SibSp' and 'Parch' columns

copy_data.rename(columns= {
    'SibSp' : 'No_of_Siblings_and_Spouses_Aboard',
    'Parch' : 'No_of_Parents_and_Children_Aboard'
},inplace=True)

In [58]:
copy_data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age',
       'No_of_Siblings_and_Spouses_Aboard',
       'No_of_Parents_and_Children_Aboard', 'Ticket', 'Fare', 'Embarked'],
      dtype='object')

Renaming column values

In [59]:
copy_data['Embarked'].value_counts()

Embarked
S     554
29    177
C     130
Q      28
Name: count, dtype: int64

In [63]:
# Renaming the Embarked column values to meaningful ones

copy_data.replace({'Embarked': {
    29 : 'Q'
}}, inplace=True)
copy_data['Embarked'].value_counts()

Embarked
S    554
Q    205
C    130
Name: count, dtype: int64

In [65]:
copy_data.replace({'Embarked' : {
    'S' : 'Southampton',
    'Q' : 'Queenstown',
    'C' : 'Cherbourg'
}}, inplace=True)
copy_data['Embarked'].value_counts()

Embarked
Southampton    554
Queenstown     205
Cherbourg      130
Name: count, dtype: int64

In [66]:
copy_data.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,No_of_Siblings_and_Spouses_Aboard,No_of_Parents_and_Children_Aboard,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,Southampton
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,Cherbourg
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,Southampton
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,Southampton
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,Southampton

In [71]:
# Adding a new column : Underage - true for passengers under 18 and False for passengers over 18

copy_data['Underage'] = copy_data['Age'] < 18

In [72]:
copy_data.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,No_of_Siblings_and_Spouses_Aboard,No_of_Parents_and_Children_Aboard,Ticket,Fare,Embarked,Underage
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,Southampton,False
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,Cherbourg,False
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,Southampton,False
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,Southampton,False
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,Southampton,False

In [73]:
copy_data.to_pickle('titanic.pkl')