## Importing and Understanding of the data

In [125]:
import pandas as pd 

original_data = pd.read_csv('../data/titanic.csv')

copy_data = original_data.copy()

In [126]:
copy_data.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Attributes and Values

In [117]:
copy_data.columns.tolist()

['PassengerId',
 'Survived',
 'Pclass',
 'Name',
 'Sex',
 'Age',
 'SibSp',
 'Parch',
 'Ticket',
 'Fare',
 'Cabin',
 'Embarked']

In [118]:
copy_data.values[0].tolist()

[1,
 0,
 3,
 'Braund, Mr. Owen Harris',
 'male',
 22.0,
 1,
 0,
 'A/5 21171',
 7.25,
 nan,
 'S']

First and last rows of the dataset

In [119]:
copy_data.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [120]:
copy_data.tail(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

Missing Values check

In [121]:
copy_data.isna().any()

PassengerId    False
Survived       False
Pclass         False
Name           False
Sex            False
Age             True
SibSp          False
Parch          False
Ticket         False
Fare           False
Cabin           True
Embarked        True
dtype: bool

Columns with Missing Values : AGE, CABIN, EMBARKED

Oldest Surviving Male & Female Passenger

In [122]:
copy_data['Survived'] = original_data['Survived']

survived_passengers = copy_data[copy_data['Survived'] == 1]

male_survived_passengers = survived_passengers[survived_passengers['Sex'] == 'male']
female_survived_passengers = survived_passengers[survived_passengers['Sex'] == 'female']

oldest_male_survived_passenger = male_survived_passengers.loc[male_survived_passengers['Age'].idxmax(), ['Name','Age']]
oldest_female_survived_passenger = female_survived_passengers.loc[female_survived_passengers['Age'].idxmax(), ['Name','Age']]

In [123]:
print(f'Oldest Male Passenger ------ {oldest_male_survived_passenger['Name']} : {oldest_male_survived_passenger['Age']}')
print(f'Oldest Female Passenger ------ {oldest_female_survived_passenger['Name']} : {oldest_female_survived_passenger['Age']}')

Oldest Male Passenger ------ Barkworth, Mr. Algernon Henry Wilson : 80.0
Oldest Female Passenger ------ Andrews, Miss. Kornelia Theodosia : 63.0

Grouping the Passengers by Sex

In [143]:
pd.set_option('display.max_columns', None)
pd.set_option('display.expand_frame_repr', False)

grouped_data = copy_data.groupby('Sex')

for sex, group in grouped_data:
    print(f'Rows for Sex: {sex}')
    print(group.head(5))

Rows for Sex: female
   PassengerId  Survived  Pclass                                               Name     Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked
1            2         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1      0          PC 17599  71.2833   C85        C
2            3         1       3                             Heikkinen, Miss. Laina  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S
3            4         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1      0            113803  53.1000  C123        S
8            9         1       3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0      2            347742  11.1333   NaN        S
9           10         1       2                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1      0            237736  30.0708   NaN        C
Rows for Sex: male
   PassengerId  Survived  Pclass                            Name   Sex   Age  SibSp  Parch     Ticket     Fare Cabin Embarked
0            1         0       3         Braund, Mr. Owen Harris  male  22.0      1      0  A/5 21171   7.2500   NaN        S
4            5         0       3        Allen, Mr. William Henry  male  35.0      0      0     373450   8.0500   NaN        S
5            6         0       3                Moran, Mr. James  male   NaN      0      0     330877   8.4583   NaN        Q
6            7         0       1         McCarthy, Mr. Timothy J  male  54.0      0      0      17463  51.8625   E46        S
7            8         0       3  Palsson, Master. Gosta Leonard  male   2.0      3      1     349909  21.0750   NaN        S

Grouping the Passengers by Pclass

In [144]:
grouped_data = copy_data.groupby('Pclass')

for Pclass, group in grouped_data:
    print(f'Rows for Passenger Class: {Pclass}')
    print(group.head(5))

Rows for Passenger Class: 1
    PassengerId  Survived  Pclass                                               Name     Sex   Age  SibSp  Parch    Ticket     Fare Cabin Embarked
1             2         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1      0  PC 17599  71.2833   C85        C
3             4         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1      0    113803  53.1000  C123        S
6             7         0       1                            McCarthy, Mr. Timothy J    male  54.0      0      0     17463  51.8625   E46        S
11           12         1       1                           Bonnell, Miss. Elizabeth  female  58.0      0      0    113783  26.5500  C103        S
23           24         1       1                       Sloper, Mr. William Thompson    male  28.0      0      0    113788  35.5000    A6        S
Rows for Passenger Class: 2
    PassengerId  Survived  Pclass                                 Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
9            10         1       2  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1      0  237736  30.0708   NaN        C
15           16         1       2     Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0      0  248706  16.0000   NaN        S
17           18         1       2         Williams, Mr. Charles Eugene    male   NaN      0      0  244373  13.0000   NaN        S
20           21         0       2                 Fynney, Mr. Joseph J    male  35.0      0      0  239865  26.0000   NaN        S
21           22         1       2                Beesley, Mr. Lawrence    male  34.0      0      0  248698  13.0000   D56        S
Rows for Passenger Class: 3
   PassengerId  Survived  Pclass                            Name     Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked
0            1         0       3         Braund, Mr. Owen Harris    male  22.0      1      0         A/5 21171   7.2500   NaN        S
2            3         1       3          Heikkinen, Miss. Laina  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S
4            5         0       3        Allen, Mr. William Henry    male  35.0      0      0            373450   8.0500   NaN        S
5            6         0       3                Moran, Mr. James    male   NaN      0      0            330877   8.4583   NaN        Q
7            8         0       3  Palsson, Master. Gosta Leonard    male   2.0      3      1            349909  21.0750   NaN        S

In [145]:
pd.reset_option('display.max_columns')
pd.reset_option('display.expand_frame_repr')